# Generated by Django 4.1.4 on 2022-12-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmb_marca', models.CharField(max_length=20)),
                ('nmb_mod', models.CharField(max_length=30)),
                ('id_mod', models.CharField(max_length=20)),
                ('car_esp', models.CharField(max_length=20)),
                ('fecha_prod', models.CharField(max_length=9)),
                ('default_motor', models.CharField(max_length=20)),
                ('transm', models.CharField(max_length=20)),
                ('precio_prom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmb_motor', models.CharField(max_length=20)),
                ('hp_default', models.IntegerField()),
                ('cil', models.CharField(max_length=20)),
                ('hp_max', models.IntegerField()),
                ('precio_prom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=20)),
            ],
        ),
    ]
